<?php

namespace ContainerHzejJAA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getColorRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ColorRepository' shared autowired service.
     *
     * @return \App\Repository\ColorRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ColorRepository.php';

        return $container->privates['App\\Repository\\ColorRepository'] = new \App\Repository\ColorRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
