<?php

namespace ContainerHzejJAA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEasyAdminSlugSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\EasyAdminSlugSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\EasyAdminSlugSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/EasyAdminSlugSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        return $container->privates['App\\EventSubscriber\\EasyAdminSlugSubscriber'] = new \App\EventSubscriber\EasyAdminSlugSubscriber(($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('fr')));
    }
}
