<?php

namespace ContainerHzejJAA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnergyRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\EnergyRepository' shared autowired service.
     *
     * @return \App\Repository\EnergyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/EnergyRepository.php';

        return $container->privates['App\\Repository\\EnergyRepository'] = new \App\Repository\EnergyRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
