<?php

namespace ContainerHzejJAA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImagesRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ImagesRepository' shared autowired service.
     *
     * @return \App\Repository\ImagesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ImagesRepository.php';

        return $container->privates['App\\Repository\\ImagesRepository'] = new \App\Repository\ImagesRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
